[workspace]
members = [
    "phorcys-config",
    "phorcys-osc",
    "phorcys-examples",
    "phorcys-miditable",
    "exparam-server",
    "vrcosc-clock",
]

[profile.production]
inherits = "release"
lto = "fat"
strip = "symbols"
